# https://golangci-lint.run/usage/configuration/
run:
  concurrency: 4
  timeout: 5m
  tests: true
  issues-exit-code: 1
  go: '1.20'
output:
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: false
  uniq-by-line: false
  path-prefix: ""
  sort-results: false
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - funlen
    - goimports
    - godot
    - ireturn
    - lll
    - unparam
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
